export const ADD_TODO_LIST_ITEM = 'ADD_TODO_LIST_ITEM'
export const DELETE_TODO_LIST_ITEM = 'DELETE_TODO_LIST_ITEM'
export const EDIT_TODO_LIST_ITEM = 'EDIT_TODO_LIST_ITEM'
export const LOAD_TODO_LIST = 'LOAD_TODO_LIST'
