export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGIN_MUTATION = 'AUTH_LOGIN_MUTATION'
export const AUTH_VERIFY_EMAIL_MUTATION = 'AUTH_VERIFY_EMAIL_MUTATION'
